


export const MAIN_API_URL = 'MAIN_API_URL';
export const FORECAST_API_URL = 'FORECAST_API_URL';

export const USER_COORDINATES = 'USER_COORDINATES';
export const USER_WEATHER_FROM_COORDINATES = 'USER_WEATHER_FROM_COORDINATES';
export const REQUEST_API_RESULT = 'REQUEST_API_RESULT_NOT_FOUND';



export const RECEIVE_FORECAST = 'RECEIVE_FORECAST';
export const REQUEST_FORECAST = 'REQUEST_FORECAST';

